[baxter]
dof=5
T=10
scaling=0.1
period=1
dt=0.1
D=0.3

[dataset]
num_data=250000
deviation=0.05
dataset_filename="5DOF3SecDelayTrajCondRandomized0.05ToMinus0.05500k"
test_size=0.1
batch_size=1024
random_state=1
device_name="cuda"
dagger=true
batch_size_dagger=512
num_data_dagger=10000
deviation_dagger=0.05
