[baxter]
dof=4
T=10
scaling=0.1
period=0.5
dt=0.1
D=0.5

[dataset]
num_data=50000
deviation=0.1
dataset_filename="5DOFShortDelayTrajCondRandomized0.2ToMinus0.2250k"
test_size=0.1
batch_size=128
random_state=1
device_name="cpu"
