[model]
model_filename="fno"
model_type="FNO"
epochs=250
learning_rate=3e-3
weight_decay=2e-6
gamma=0.99
iters_dag=5
epochs_dag=50
learning_rate_dag=3e-3
weight_decay_dag=1.5e-2
gamma_dag=0.98
device_name="cuda"

[FNO]
hidden_size=128
modes=20
num_layers=2
# Will be overwritten such that input_channel = 3*dof and output_channel = 2*dof
input_channel=0
output_channel=0
