[model]
# Will be overwritten such that model_filename is same as data_filename for ease of use
model_filename="gru"
model_type="GRU"
epochs=100
learning_rate=0.0003
weight_decay=1.5e-2
gamma=0.98
device_name="cpu"

[GRU]
hidden_size=64
num_layers=5
# Will be overwritten such that input_channel = 3*dof and output_channel = 2*dof
input_channel=0
output_channel=0
